package org.hyatt.model;
// Generated 2017-8-10 18:56:01 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "Item")
public class Item implements java.io.Serializable {

	private long id;
	private int cost;
	private String localizedName;
	private String name;
	private int recipe;
	private int secretShop;
	private int sideShop;

	public Item() {
	}

	public Item(long id, int cost, int recipe, int secretShop, int sideShop) {
		this.id = id;
		this.cost = cost;
		this.recipe = recipe;
		this.secretShop = secretShop;
		this.sideShop = sideShop;
	}

	public Item(long id, int cost, String localizedName, String name, int recipe, int secretShop, int sideShop) {
		this.id = id;
		this.cost = cost;
		this.localizedName = localizedName;
		this.name = name;
		this.recipe = recipe;
		this.secretShop = secretShop;
		this.sideShop = sideShop;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "cost", nullable = false)
	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	@Column(name = "localized_name")
	public String getLocalizedName() {
		return this.localizedName;
	}

	public void setLocalizedName(String localizedName) {
		this.localizedName = localizedName;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "recipe", nullable = false)
	public int getRecipe() {
		return this.recipe;
	}

	public void setRecipe(int recipe) {
		this.recipe = recipe;
	}

	@Column(name = "secret_shop", nullable = false)
	public int getSecretShop() {
		return this.secretShop;
	}

	public void setSecretShop(int secretShop) {
		this.secretShop = secretShop;
	}

	@Column(name = "side_shop", nullable = false)
	public int getSideShop() {
		return this.sideShop;
	}

	public void setSideShop(int sideShop) {
		this.sideShop = sideShop;
	}

}
