package org.hyatt.model;
// Generated 2017-8-15 9:38:11 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * League generated by hbm2java
 */
@Entity
@Table(name = "League")
public class League implements java.io.Serializable {

	private long leagueid;
	private String description;
	private long itemdef;
	private String name;
	private String tournamentUrl;

	public League() {
	}

	public League(long leagueid, long itemdef) {
		this.leagueid = leagueid;
		this.itemdef = itemdef;
	}

	public League(long leagueid, String description, long itemdef, String name, String tournamentUrl) {
		this.leagueid = leagueid;
		this.description = description;
		this.itemdef = itemdef;
		this.name = name;
		this.tournamentUrl = tournamentUrl;
	}

	@Id

	@Column(name = "leagueid", unique = true, nullable = false)
	public long getLeagueid() {
		return this.leagueid;
	}

	public void setLeagueid(long leagueid) {
		this.leagueid = leagueid;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "itemdef", nullable = false)
	public long getItemdef() {
		return this.itemdef;
	}

	public void setItemdef(long itemdef) {
		this.itemdef = itemdef;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "tournament_url")
	public String getTournamentUrl() {
		return this.tournamentUrl;
	}

	public void setTournamentUrl(String tournamentUrl) {
		this.tournamentUrl = tournamentUrl;
	}

}
