package org.hyatt.model;
// Generated 2017-8-10 18:56:01 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MatchObj generated by hbm2java
 */
@Entity
@Table(name = "MatchObj")
public class MatchObj implements java.io.Serializable {

	private long id;
	private int direTeamId;
	private int lobbyTime;
	private long matchId;
	private long matchSeqNum;
	private int radiantTeamId;
	private int seriesId;
	private int seriesType;
	private long startTime;

	public MatchObj() {
	}

	public MatchObj(long id, int direTeamId, int lobbyTime, long matchId, long matchSeqNum, int radiantTeamId,
			int seriesId, int seriesType, long startTime) {
		this.id = id;
		this.direTeamId = direTeamId;
		this.lobbyTime = lobbyTime;
		this.matchId = matchId;
		this.matchSeqNum = matchSeqNum;
		this.radiantTeamId = radiantTeamId;
		this.seriesId = seriesId;
		this.seriesType = seriesType;
		this.startTime = startTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "dire_team_id", nullable = false)
	public int getDireTeamId() {
		return this.direTeamId;
	}

	public void setDireTeamId(int direTeamId) {
		this.direTeamId = direTeamId;
	}

	@Column(name = "lobby_time", nullable = false)
	public int getLobbyTime() {
		return this.lobbyTime;
	}

	public void setLobbyTime(int lobbyTime) {
		this.lobbyTime = lobbyTime;
	}

	@Column(name = "match_id", nullable = false)
	public long getMatchId() {
		return this.matchId;
	}

	public void setMatchId(long matchId) {
		this.matchId = matchId;
	}

	@Column(name = "match_seq_num", nullable = false)
	public long getMatchSeqNum() {
		return this.matchSeqNum;
	}

	public void setMatchSeqNum(long matchSeqNum) {
		this.matchSeqNum = matchSeqNum;
	}

	@Column(name = "radiant_team_id", nullable = false)
	public int getRadiantTeamId() {
		return this.radiantTeamId;
	}

	public void setRadiantTeamId(int radiantTeamId) {
		this.radiantTeamId = radiantTeamId;
	}

	@Column(name = "series_id", nullable = false)
	public int getSeriesId() {
		return this.seriesId;
	}

	public void setSeriesId(int seriesId) {
		this.seriesId = seriesId;
	}

	@Column(name = "series_type", nullable = false)
	public int getSeriesType() {
		return this.seriesType;
	}

	public void setSeriesType(int seriesType) {
		this.seriesType = seriesType;
	}

	@Column(name = "start_time", nullable = false)
	public long getStartTime() {
		return this.startTime;
	}

	public void setStartTime(long startTime) {
		this.startTime = startTime;
	}

}
