package org.hyatt.model;
// Generated 2017-8-10 18:56:01 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MatchObjPlayerId generated by hbm2java
 */
@Embeddable
public class MatchObjPlayerId implements java.io.Serializable {

	private long matchesId;
	private long playersId;

	public MatchObjPlayerId() {
	}

	public MatchObjPlayerId(long matchesId, long playersId) {
		this.matchesId = matchesId;
		this.playersId = playersId;
	}

	@Column(name = "matches_id", nullable = false)
	public long getMatchesId() {
		return this.matchesId;
	}

	public void setMatchesId(long matchesId) {
		this.matchesId = matchesId;
	}

	@Column(name = "players_id", nullable = false)
	public long getPlayersId() {
		return this.playersId;
	}

	public void setPlayersId(long playersId) {
		this.playersId = playersId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatchObjPlayerId))
			return false;
		MatchObjPlayerId castOther = (MatchObjPlayerId) other;

		return (this.getMatchesId() == castOther.getMatchesId()) && (this.getPlayersId() == castOther.getPlayersId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMatchesId();
		result = 37 * result + (int) this.getPlayersId();
		return result;
	}

}
