package org.hyatt.model;
// Generated 2017-8-10 18:56:01 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Player generated by hbm2java
 */
@Entity
@Table(name = "Player")
public class Player implements java.io.Serializable {

	private long id;
	private long accountId;
	private Long heroId;
	private int playerSlot;

	public Player() {
	}

	public Player(long id, long accountId, int playerSlot) {
		this.id = id;
		this.accountId = accountId;
		this.playerSlot = playerSlot;
	}

	public Player(long id, long accountId, Long heroId, int playerSlot) {
		this.id = id;
		this.accountId = accountId;
		this.heroId = heroId;
		this.playerSlot = playerSlot;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "account_id", nullable = false)
	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "hero_id")
	public Long getHeroId() {
		return this.heroId;
	}

	public void setHeroId(Long heroId) {
		this.heroId = heroId;
	}

	@Column(name = "player_slot", nullable = false)
	public int getPlayerSlot() {
		return this.playerSlot;
	}

	public void setPlayerSlot(int playerSlot) {
		this.playerSlot = playerSlot;
	}

}
