package org.hyatt.model;
// Generated 2017-8-16 9:53:24 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stats generated by hbm2java
 */
@Entity
@Table(name = "Stats")
public class Stats implements java.io.Serializable {

	private long id;
	private String clusterDict;
	private String gmDict;
	private Date lastTime;
	private Date startTime;
	private long totalcount;
	private Date updatetime;

	public Stats() {
	}

	public Stats(long id, long totalcount) {
		this.id = id;
		this.totalcount = totalcount;
	}

	public Stats(long id, String clusterDict, String gmDict, Date lastTime, Date startTime, long totalcount,
			Date updatetime) {
		this.id = id;
		this.clusterDict = clusterDict;
		this.gmDict = gmDict;
		this.lastTime = lastTime;
		this.startTime = startTime;
		this.totalcount = totalcount;
		this.updatetime = updatetime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "cluster_dict")
	public String getClusterDict() {
		return this.clusterDict;
	}

	public void setClusterDict(String clusterDict) {
		this.clusterDict = clusterDict;
	}

	@Column(name = "gm_dict")
	public String getGmDict() {
		return this.gmDict;
	}

	public void setGmDict(String gmDict) {
		this.gmDict = gmDict;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_time", length = 19)
	public Date getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Column(name = "totalcount", nullable = false)
	public long getTotalcount() {
		return this.totalcount;
	}

	public void setTotalcount(long totalcount) {
		this.totalcount = totalcount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Override
	public String toString() {
		return "Stats [id=" + id + ", clusterDict=" + clusterDict + ", gmDict=" + gmDict + ", lastTime=" + lastTime
				+ ", startTime=" + startTime + ", totalcount=" + totalcount + ", updatetime=" + updatetime + "]";
	}
	
	

}
